site_name: Temperature, Pressure and Effective Thermal Conductivity Recorder Manual
site_url: https://Kiki-Schreibt.github.io/t_p_etc_recorder_v2/


theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            options:
              show_source: true
              show_root_heading: true
              show_submodules: false
            paths:
              - src
  - gen-files:
      scripts:
        - docs/gen_api_v2.py
  - awesome-pages


nav:
  - index.md
  - User Manual:
      - Overview: user_manual/overview.md

      - Getting Started:
        - Installation: user_manual/getting_started/installation.md
        - Configuration Creation: user_manual/getting_started/config_creation.md
        - Start New Test: user_manual/getting_started/create_new_test.md
      - Main Window: user_manual/main_window.md
      - Database: user_manual/database/database_tables.md

  - API: api/index.md
