site_name: Temperature, Pressure and Effective Thermal Conductivity Recorder Manual
site_url: https://Kiki-Schreibt.github.io/t_p_etc_recorder_v2/

nav:
  - index.md
  - User Manual:
      - Installation: User_Manual/Installation.md
      - Main_Window: User_Manual/General.md
      - Create_New_Test: User_Manual/Create_New_Test.md
theme:
  name: material



